[package]
name = "football-one"
version = "0.1.0"
authors = ["hos"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1.5.4"
serde = { version = "1.0.118", features = ["derive"] }
toml = "0.5.8"